// <auto-generated />
namespace HRBadging.Migrations.HR
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GoodSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoodSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201810110349123_GoodSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
